[[experiment]]
name = "agentic-routing-policies-billing-qwq32b"
script = "agentic_routing_policies_billing.py"
model = "qwq-32b"
topology = "topologies/optimizing_billing_policy.csv"
prompts_dir = "prompts/optimizing_billing_policy"
final_report_prompt = "prompts/optimizing_billing_policy/final-report.txt"
log_dir = "logs/optimizing_billing_policy/qwq-32b"

[[experiment]]
name = "agentic-routing-policies-as7007-qwq32b"
script = "agentic_routing_policies.py"
model = "qwq-32b"
topology = "topologies/as7007.csv"
prompts_dir = "prompts/as7007"
final_report_prompt = "prompts/as7007/final-report.txt"
log_dir = "logs/as7007/qwq-32b"
